services:
  mahler:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./mp3:/app/mp3:ro
      - ./app/templates:/app/templates:ro
      - ./app/static:/app/static:ro
